### ISSUE TITLE
可以编译一个MacOS版本的吗

### ISSUE THREAD

**Issue by AezwxLOkCzw** [copbint/clipPicture2base64#1]

**Comment by copbint** [comment]
不好意思，我没有mac环境

**Comment by AezwxLOkCzw** [comment]
没关系，我昨天找到一个Chrome插件，挺有帮助的。
![image](https://user-images.githubusercontent.com/54979250/188309860-3fbc459e-be20-4b33-9d38-f78722f15cd1.png)
